import {
  DateDisplayFormat,
  FieldMetadataType,
  RelationOnDeleteAction,
  RelationType,
} from 'twenty-shared/types';

import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';
import { getTsVectorColumnExpressionFromFields } from 'src/engine/workspace-manager/utils/get-ts-vector-column-expression.util';
import { SEARCH_FIELDS_FOR_LEAD } from 'src/modules/lead/standard-objects/lead.workspace-entity';

export const buildLeadStandardFlatFieldMetadatas = ({
  now,
  objectName,
  workspaceId,
  standardObjectMetadataRelatedEntityIds,
  dependencyFlatEntityMaps,
  twentyStandardApplicationId,
}: Omit<
  CreateStandardFieldArgs<'lead', FieldMetadataType>,
  'context'
>): Record<AllStandardObjectFieldName<'lead'>, FlatFieldMetadata> => ({
  // Base fields from BaseWorkspaceEntity
  id: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: 'Id',
      description: 'Id',
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: 'uuid',
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: 'Creation date',
      description: 'Creation date',
      icon: 'IconCalendar',
      isSystem: true,
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: 'now',
      settings: {
        displayFormat: DateDisplayFormat.RELATIVE,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: 'Last update',
      description: 'Last time the record was changed',
      icon: 'IconCalendarClock',
      isSystem: true,
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: 'now',
      settings: {
        displayFormat: DateDisplayFormat.RELATIVE,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: 'Deleted at',
      description: 'Date when the record was deleted',
      icon: 'IconCalendarMinus',
      isSystem: true,
      isNullable: true,
      isUIReadOnly: true,
      settings: {
        displayFormat: DateDisplayFormat.RELATIVE,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  position: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'position',
      type: FieldMetadataType.POSITION,
      label: 'Position',
      description: 'Lead record position',
      icon: 'IconHierarchy2',
      isSystem: true,
      isNullable: false,
      defaultValue: 0,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdBy',
      type: FieldMetadataType.ACTOR,
      label: 'Created by',
      description: 'The creator of the record',
      icon: 'IconCreativeCommonsSa',
      isSystem: true,
      isUIReadOnly: true,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedBy',
      type: FieldMetadataType.ACTOR,
      label: 'Updated by',
      description: 'The workspace member who last updated the record',
      icon: 'IconUserCircle',
      isSystem: true,
      isUIReadOnly: true,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchVector: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'searchVector',
      type: FieldMetadataType.TS_VECTOR,
      label: 'Search vector',
      description: 'Field used for full-text search',
      icon: 'IconUser',
      isSystem: true,
      isNullable: true,
      settings: {
        generatedType: 'STORED',
        asExpression: getTsVectorColumnExpressionFromFields(
          SEARCH_FIELDS_FOR_LEAD,
        ),
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // Lead-specific fields
  name: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'name',
      type: FieldMetadataType.TEXT,
      label: 'Name',
      description: 'The lead name',
      icon: 'IconUser',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  emails: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'emails',
      type: FieldMetadataType.EMAILS,
      label: 'Emails',
      description: 'Lead emails',
      icon: 'IconMail',
      isNullable: false,
      settings: {
        maxNumberOfValues: 5,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  phones: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'phones',
      type: FieldMetadataType.PHONES,
      label: 'Phones',
      description: 'Lead phones',
      icon: 'IconPhone',
      isNullable: false,
      settings: {
        maxNumberOfValues: 5,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  source: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'source',
      type: FieldMetadataType.SELECT,
      label: 'Source',
      description: 'Lead source',
      icon: 'IconWorld',
      isNullable: false,
      defaultValue: "'WEBSITE'",
      options: [
        {
          id: '30303030-a100-4000-8000-000000000000',
          value: 'WEBSITE',
          label: 'Website',
          position: 0,
          color: 'green',
        },
        {
          id: '30303030-a101-4000-8000-000000000000',
          value: 'REFERRAL',
          label: 'Referral',
          position: 1,
          color: 'blue',
        },
        {
          id: '30303030-a102-4000-8000-000000000000',
          value: 'COLD_OUTREACH',
          label: 'Cold Outreach',
          position: 2,
          color: 'purple',
        },
        {
          id: '30303030-a103-4000-8000-000000000000',
          value: 'SOCIAL_MEDIA',
          label: 'Social Media',
          position: 3,
          color: 'sky',
        },
        {
          id: '30303030-a104-4000-8000-000000000000',
          value: 'PAID_AD',
          label: 'Paid Ad',
          position: 4,
          color: 'orange',
        },
        {
          id: '30303030-a105-4000-8000-000000000000',
          value: 'EVENT',
          label: 'Event',
          position: 5,
          color: 'turquoise',
        },
        {
          id: '30303030-a106-4000-8000-000000000000',
          value: 'PARTNER',
          label: 'Partner',
          position: 6,
          color: 'pink',
        },
        {
          id: '30303030-a107-4000-8000-000000000000',
          value: 'OTHER',
          label: 'Other',
          position: 7,
          color: 'gray',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  sourceDetail: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'sourceDetail',
      type: FieldMetadataType.TEXT,
      label: 'Source Detail',
      description: 'Lead source detail',
      icon: 'IconInfoCircle',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  needs: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'needs',
      type: FieldMetadataType.TEXT,
      label: 'Needs',
      description: 'Lead needs',
      icon: 'IconTarget',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  stage: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'stage',
      type: FieldMetadataType.SELECT,
      label: 'Stage',
      description: 'Lead stage',
      icon: 'IconProgressCheck',
      isNullable: false,
      defaultValue: "'NEW'",
      options: [
        {
          id: '30303030-b100-4000-8000-000000000000',
          value: 'NEW',
          label: 'New',
          position: 0,
          color: 'red',
        },
        {
          id: '30303030-b101-4000-8000-000000000000',
          value: 'CONTACTED',
          label: 'Contacted',
          position: 1,
          color: 'orange',
        },
        {
          id: '30303030-b102-4000-8000-000000000000',
          value: 'QUALIFIED',
          label: 'Qualified',
          position: 2,
          color: 'yellow',
        },
        {
          id: '30303030-b103-4000-8000-000000000000',
          value: 'PRE_CALL',
          label: 'Pre-call',
          position: 3,
          color: 'sky',
        },
        {
          id: '30303030-b104-4000-8000-000000000000',
          value: 'MEETING_SCHEDULED',
          label: 'Meeting Scheduled',
          position: 4,
          color: 'blue',
        },
        {
          id: '30303030-b105-4000-8000-000000000000',
          value: 'PROPOSAL',
          label: 'Proposal',
          position: 5,
          color: 'purple',
        },
        {
          id: '30303030-b106-4000-8000-000000000000',
          value: 'NEGOTIATION',
          label: 'Negotiation',
          position: 6,
          color: 'pink',
        },
        {
          id: '30303030-b107-4000-8000-000000000000',
          value: 'WON',
          label: 'Won',
          position: 7,
          color: 'green',
        },
        {
          id: '30303030-b108-4000-8000-000000000000',
          value: 'LOST',
          label: 'Lost',
          position: 8,
          color: 'gray',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  priority: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'priority',
      type: FieldMetadataType.SELECT,
      label: 'Priority',
      description: 'Lead priority',
      icon: 'IconFlag',
      isNullable: false,
      defaultValue: "'MEDIUM'",
      options: [
        {
          id: '30303030-c100-4000-8000-000000000000',
          value: 'LOW',
          label: 'Low',
          position: 0,
          color: 'gray',
        },
        {
          id: '30303030-c101-4000-8000-000000000000',
          value: 'MEDIUM',
          label: 'Medium',
          position: 1,
          color: 'yellow',
        },
        {
          id: '30303030-c102-4000-8000-000000000000',
          value: 'HIGH',
          label: 'High',
          position: 2,
          color: 'orange',
        },
        {
          id: '30303030-c103-4000-8000-000000000000',
          value: 'URGENT',
          label: 'Urgent',
          position: 3,
          color: 'red',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  estimatedValue: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'estimatedValue',
      type: FieldMetadataType.CURRENCY,
      label: 'Estimated Value',
      description: 'Lead estimated value',
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  nextFollowUpDate: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'nextFollowUpDate',
      type: FieldMetadataType.DATE_TIME,
      label: 'Next Follow-up',
      description: 'Lead next follow-up date',
      icon: 'IconCalendarEvent',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  linkedinLink: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'linkedinLink',
      type: FieldMetadataType.LINKS,
      label: 'LinkedIn',
      description: 'Lead LinkedIn profile',
      icon: 'IconBrandLinkedin',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  enrichmentStatus: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'enrichmentStatus',
      type: FieldMetadataType.SELECT,
      label: 'Enrichment Status',
      description: 'Lead enrichment status',
      icon: 'IconSparkles',
      isNullable: false,
      defaultValue: "'NOT_ENRICHED'",
      options: [
        {
          id: '30303030-d100-4000-8000-000000000000',
          value: 'NOT_ENRICHED',
          label: 'Not Enriched',
          position: 0,
          color: 'gray',
        },
        {
          id: '30303030-d101-4000-8000-000000000000',
          value: 'PENDING',
          label: 'Pending',
          position: 1,
          color: 'yellow',
        },
        {
          id: '30303030-d102-4000-8000-000000000000',
          value: 'ENRICHED',
          label: 'Enriched',
          position: 2,
          color: 'green',
        },
        {
          id: '30303030-d103-4000-8000-000000000000',
          value: 'FAILED',
          label: 'Failed',
          position: 3,
          color: 'red',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  industry: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'industry',
      type: FieldMetadataType.TEXT,
      label: 'Industry',
      description: 'Lead industry',
      icon: 'IconBuildingFactory',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  companySize: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'companySize',
      type: FieldMetadataType.TEXT,
      label: 'Company Size',
      description: 'Lead company size',
      icon: 'IconUsers',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  companyRevenue: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'companyRevenue',
      type: FieldMetadataType.TEXT,
      label: 'Company Revenue',
      description: 'Lead company revenue',
      icon: 'IconReportMoney',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // Relation fields
  company: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'company',
      label: 'Company',
      description: 'Lead company',
      icon: 'IconBuildingSkyscraper',
      isNullable: true,
      targetObjectName: 'company',
      targetFieldName: 'leads',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'companyId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  assignedTo: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'assignedTo',
      label: 'Assigned To',
      description: 'Lead assigned to',
      icon: 'IconUserCircle',
      isNullable: true,
      targetObjectName: 'workspaceMember',
      targetFieldName: 'assignedLeads',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'assignedToId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  owner: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'owner',
      label: 'Owner',
      description: 'Lead owner',
      icon: 'IconUserCircle',
      isNullable: true,
      targetObjectName: 'workspaceMember',
      targetFieldName: 'ownedLeads',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'ownerId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  favorites: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'favorites',
      label: 'Favorites',
      description: 'Favorites linked to the lead',
      icon: 'IconHeart',
      isNullable: true,
      targetObjectName: 'favorite',
      targetFieldName: 'lead',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  taskTargets: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'taskTargets',
      label: 'Tasks',
      description: 'Tasks tied to the lead',
      icon: 'IconCheckbox',
      isUIReadOnly: true,
      isNullable: true,
      targetObjectName: 'taskTarget',
      targetFieldName: 'targetLead',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  noteTargets: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'noteTargets',
      label: 'Notes',
      description: 'Notes tied to the lead',
      icon: 'IconNotes',
      isUIReadOnly: true,
      isNullable: true,
      targetObjectName: 'noteTarget',
      targetFieldName: 'targetLead',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  attachments: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'attachments',
      label: 'Attachments',
      description: 'Attachments linked to the lead',
      icon: 'IconFileImport',
      isNullable: true,
      targetObjectName: 'attachment',
      targetFieldName: 'targetLead',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  timelineActivities: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'timelineActivities',
      label: 'Timeline Activities',
      description: 'Timeline Activities linked to the lead.',
      icon: 'IconTimelineEvent',
      isNullable: true,
      targetObjectName: 'timelineActivity',
      targetFieldName: 'targetLead',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
});
